# Generated by Django 5.2.5 on 2025-09-10 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fan',
            options={'verbose_name': 'Fan', 'verbose_name_plural': 'Fanlar'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Teacher', 'verbose_name_plural': 'Oqituvchilar'},
        ),
        migrations.AlterModelOptions(
            name='yonalish',
            options={'verbose_name': 'Yonalish', 'verbose_name_plural': 'Yonalishlar'},
        ),
    ]
